global using AtendeLogo.Application.Abstractions.Services;
global using AtendeLogo.Application.Events;
global using AtendeLogo.TestCommon.Mocks.Infrastructure;
global using AtendeLogo.TestCommon.Mocks.Repositories;
global using AtendeLogo.Domain.Primitives;
global using AtendeLogo.Shared.Enums;
global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
global using AtendeLogo.Domain.Primitives.Abstractions;
global using AtendeLogo.Shared.Constants;
global using AtendeLogo.Shared.Interfaces.Identities;
global using AtendeLogo.Common;
global using AtendeLogo.Persistence.Common.Configurations;
global using AtendeLogo.Application.Abstractions.Persistence.Activities;
global using AtendeLogo.Application.Abstractions.Security;
global using AtendeLogo.Persistence.Identity;
global using AtendeLogo.Shared.Abstractions;

global using Xunit.Abstractions;
